name: Build Electron App for macOS, Windows, and Linux

on:
  push:
    branches:
      - main

jobs:
  build-macos:
    uses: ./.github/workflows/common-build.yml
    with:
      platform-name: macos-latest
#  build-windows:
#    uses: ./.github/workflows/common-build.yml
#    with:
#      platform-name: windows-latest
#
#  build-linux:
#    uses: ./.github/workflows/common-build.yml
#    with:
#      platform-name: ubuntu-latest
