name: Build Electron App for macOS, Windows, and Linux

on:
  push:
    branches:
      - main

jobs:
   test-macos:
     uses: ./.github/workflows/common-build.yml
     with:
       platform-name: macos-latest
