name: Build Electron App for macOS, Windows, and Linux

on:
  push:
    branches:
      - main

jobs:
   test-linux:
     uses: ./.github/workflows/common-build.yml
     with:
       platform-name: ubuntu-latest
