name: Common Build Workflow

on:
  workflow_call:
    inputs:
      platform-name:
        required: true
        type: string

jobs:
  build_and_test:
    runs-on: ${{ inputs.platform-name }}
    env:
      NX_SKIP_NX_CACHE: true
      PLATFORM: ${{ inputs.platform-name }}
      ELECTRON_RENDERER_URL: 'http://localhost:4200'
      FLASHCARD_TEMPLATES_BASE_URL: 'http://localhost:5000'


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Download JmDict
        run: |
          wget -O jmdict-all.json.zip https://github.com/scriptin/jmdict-simplified/releases/download/3.5.0%2B20240826121924/jmdict-all-3.5.0+20240826121924.json.zip

      - name: Extract JMdict ZIP and Copy to extraResources
        run: |
          unzip jmdict-all.json.zip
          mkdir -p extraResources
          cp jmdict-all-3.5.0.json extraResources/

      - name: Create ImmersionPlayer folder
        run: mkdir -p "$HOME/ImmersionPlayer"

      - name: Copy example folders to ImmersionPlayer
        run: |
          cp -R "assets/Example E01" "$HOME/ImmersionPlayer/"
          cp -R "assets/Example E02" "$HOME/ImmersionPlayer/"

      - name: Run Unit Tests
        run: npx nx run-many --target=test --passWithNoTests

      - name: Build Electron
        run: npx nx run immersion-player-desktop:build

      - name: Start player dev server
        run: npx nx run immersion-player-ui:serve &

      - name: Wait for player dev server
        run: npx wait-on $ELECTRON_RENDERER_URL

      - name: Run player E2E Tests
        run: npx nx run immersion-player-desktop:e2e

      - name: Start flashcard preview dev server
        run: npx nx run flashcard-preview:serve --port $FLASHCARD_TEMPLATES_BASE_URL &

      - name: Run flashcard preview E2E Tests
        run: npx nx run flashcard-preview:e2e

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
