name: Common Build Workflow

on:
  workflow_call:
    inputs:
      platform-name:
        required: true
        type: string

jobs:
  build_and_test:
    runs-on: ${{ inputs.platform-name }}
    env:
      NX_SKIP_NX_CACHE: true
      PLATFORM: ${{ inputs.platform-name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Download JmDict
        run: |
          wget -O jmdict-all.json.zip https://github.com/scriptin/jmdict-simplified/releases/download/3.5.0%2B20240826121924/jmdict-all-3.5.0+20240826121924.json.zip

      - name: Extract JMdict ZIP
        run: |
          unzip jmdict-all.json.zip

      - name: Run Unit Tests
        run: npx nx run-many --target=test

#      - name: Build Electron App
#        run: npm run make

#      - name: Create Library folder
#        run: mkdir -p $HOME/ImmersionPlayer
#
#      - name: Copy Test files
#        run: cp "./Example E01.mp4" "./Example E02.mp4" "$HOME/ImmersionPlayer"
#        shell: bash
#
#      - name: Run playwright tests
#        run: npx nx e2e immersion-player-desktop




