name: Common Build Workflow

on:
  workflow_call:
    inputs:
      platform-name:
        required: true
        type: string

jobs:
  build_and_test:
    runs-on: ${{ inputs.platform-name }}
    env:
      NX_SKIP_NX_CACHE: true
      PLATFORM: ${{ inputs.platform-name }}
      ELECTRON_RENDERER_URL: 'http://localhost:4200'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t immersion-player-app .

      - name: Run Typecheck in Docker
        run: docker run --rm immersion-player-app npx nx run immersion-player-desktop:typecheck

      - name: Run Unit Tests in Docker
        run: docker run --rm immersion-player-app npx nx run-many --target=test --passWithNoTests

      - name: Run E2E Tests in Docker
        run: |
          docker run --name test-container immersion-player-app /bin/bash -c "npx nx run immersion-player-desktop:e2e --workers 1 && npx nx run flashcard-preview:e2e"
          docker cp test-container:/app/playwright-report ./playwright-report || true
          docker cp test-container:/app/videos ./videos || true
          docker rm test-container

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: e2e-videos
          path: videos/
          retention-days: 30
