name: Common Build Workflow

on:
  workflow_call:
    inputs:
      platform-name:
        required: true
        type: string

jobs:
  build_and_test:
    runs-on: ${{ inputs.platform-name }}
    env:
      NX_SKIP_NX_CACHE: true
      PLATFORM: ${{ inputs.platform-name }}
      ELECTRON_RENDERER_URL: "http://localhost:4200"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Download JmDict
        run: |
          wget -O jmdict-all.json.zip https://github.com/scriptin/jmdict-simplified/releases/download/3.5.0%2B20240826121924/jmdict-all-3.5.0+20240826121924.json.zip

      - name: Extract JMdict ZIP and Copy to extraResources
        run: |
          unzip jmdict-all.json.zip
          mkdir -p extraResources
          cp jmdict-all-3.5.0.json extraResources/

      - name: Run Unit Tests
        run: npx nx run-many --target=test --passWithNoTests

      - name: Start dev server
        run: npx nx run immersion-player-ui:serve &

      - name: Wait for dev server
        run: npx wait-on $ELECTRON_RENDERER_URL

      - name: Run E2E Tests
        run: npx nx run immersion-player-desktop:e2e






